project_id = "ptcagwncwtuvcuqlwdzj"

[functions.create-user]
verify_jwt = false

[functions.test-chatwoot-connection]
verify_jwt = false

[functions.set-user-password]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.create-chatwoot-contact]
verify_jwt = false

[functions.delete-lead]
verify_jwt = false

[functions.log-resolution]
verify_jwt = false

[functions.push-all-labels-to-chatwoot]
verify_jwt = false

[functions.sync-chatwoot-labels]
verify_jwt = false

[functions.update-chatwoot-contact-labels]
verify_jwt = false

[functions.sync-chatwoot-contacts]
verify_jwt = false

[functions.super-admin-kpis]
verify_jwt = false

[functions.fix-resolution-logs]
verify_jwt = false

[functions.fetch-chatwoot-metrics]
verify_jwt = false

[functions.super-admin-kpis]
verify_jwt = false